name       : haskell-th-lift
version    : 0.7.10
release    : 2
source     :
    - https://hackage.haskell.org/package/th-lift-0.7.10/th-lift-0.7.10.tar.gz : b9ce47a1e5e50d273606e826c1210b724f1af2f302a1de71cd5c9297724d888d
license    :
    - BSD-3-Clause
    - GPL-2.0
component  : programming.haskell
summary    : Derive Template Haskell's Lift class for datatypes.
description: "Derive Template Haskell's Lift class for datatypes. \n"
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-th-abstraction
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
