name       : haskell-th-lift
version    : 0.7.6
release    : 1
source     :
    - http://hackage.haskell.org/package/th-lift-0.7.6/th-lift-0.7.6.tar.gz : 326a2c9dac32506d5b7e5d9f3234c0e7a33a612256e4745bfb8de5a32803ecd1
license    :
    - BSD-3-Clause
    - GPL-2.0
component  : programming.haskell
summary    : Derive Template Haskell's Lift class for datatypes. 
description: |
    Derive Template Haskell's Lift class for datatypes. 
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
