name       : haskell-th-lift
version    : 0.8.1
release    : 3
source     :
    - https://hackage.haskell.org/package/th-lift-0.8.1/th-lift-0.8.1.tar.gz : 3fa1f4193794d8d6dc7864e20a2f89ab268c321a4b3d254fd38282619f8e5ed7
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : programming.haskell
summary    : Derive Template Haskell's Lift class for datatypes.
description: |
    Derive Template Haskell's Lift class for datatypes.
builddeps  :
    - haskell-cabal-install
    - haskell-th-abstraction-devel
rundeps    :
    - devel:
        - haskell-th-abstraction-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
